nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']  # Ou spécifie des origines précises
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: []
        max_age: 3600